spring.application.name=CasinoCore
spring.datasource.url=jdbc:postgresql://localhost:5432/casinocore
spring.datasource.username=casino
spring.datasource.password=casino
spring.jpa.hibernate.ddl-auto=update

spring.session.store-type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
