spring.application.name=CasinoCore
spring.datasource.url=jdbc:postgresql://localhost:5432/casinocore
spring.datasource.username=casino
spring.datasource.password=casino
spring.jpa.hibernate.ddl-auto=update
